---
- hosts: all
  become: yes
  tasks:
    - name: Install OpenSSH Server
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
